FROM raspbian/stretch:latest

run apt-get clean && apt-get update && apt-get -y upgrade

run apt -y install vlc

workdir /home
add ./vlc_http_stream.sh ./vlc_http_stream.sh

cmd ["sh", "vlc_http_stream.sh"]
