version: '3.0'
services:
        simple-rtsp:
                container_name: simple-rtsp
                hostname: rtsp
                image: aler9/rtsp-simple-server

        ffmpeg:
                container_name: ffmpeg
                hostname: ffmpeg
                build: ffmpeg
                privileged: true
                volumes:
                        - ./video_stream/:/home/video_stream
                devices: 
                        - /dev/vchiq
                        - /dev/snd:/dev/snd
                env_file:
                        - .env

        vlc: 
                container_name: vlc
                hostname: vlc
                build: vlc
                env_file:
                        - .env
                ports:
                        - "8080:8080"
