version: '3.0'
services:
        rtsp:
                container_name: simple-rtsp
                hostname: rtsp
                image: aler9/rtsp-simple-server

        ffmpeg:
                container_name: ffmpeg
                hostname: ffmpeg
                build: ffmpeg
                privileged: true
              # environment:
              #         RSTP_HOST_PORT: 8554
              #         RSTP_HOST_PATH: /picam
                volumes:
                        - ./video_stream/:/home/video_stream
                devices: 
                        - /dev/vchiq
                        - /dev/snd:/dev/snd
                env_file:
                        - .env

        vlc: 
                container_name: vlc
                hostname: vlc
                build: vlc
              # environment:
              #         HTTP_STREAM_PORT: 8081
              #         RSTP_HOST_PORT: 8554
              #         RSTP_HOST_PATH: /picam
                env_file:
                        - .env

        


