version: '3.0'
services:
        simple-rtsp:
                container_name: simple-rtsp
                hostname: rtsp
                image: aler9/rtsp-simple-server
                restart: always
                
        ffmpeg:
                container_name: ffmpeg
                hostname: ffmpeg
                build: ffmpeg
                privileged: true
                volumes:
                        - ./video_stream/:/home/video_stream
                devices: 
                        - /dev/vchiq
                        - /dev/snd:/dev/snd
                env_file:
                        - .env

                restart: always
        vlc: 
                container_name: vlc
                hostname: vlc
                build: vlc
                env_file:
                        - .env
                ports:
                        - "8080:8080"
                restart: always
#        nginx:
#                container_name: nginx
#                hostname: nginx
#                build: nginx
#                ports:
#                        - "80:80"
#                        - "443:443"
#                volumes:
#                        - ./nginx/html:/usr/share/nginx/html
#                restart: always
